POST http://localhost:3003/api/blogs HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImVra3Vqb2tpbmVuIiwiaWQiOiI1ZmY0NGQ2Njk1MTdkYzRiMDA5MjM4ODIiLCJpYXQiOjE2MDk4NDYxMzl9.RQKVwMq4Bc9mfO2eLrhBr2xdbKgwTFGAE43sv6Z_V6k

{
    "title": "Using Node.js with Ekku",
    "author": "EkkuJ",
    "url": "https://ekkujokinen.com",
    "likes": 0
}